export const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/img_1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 1,
      numReviews: 10,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/img_2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/img_3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/img_4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/img_5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/img_1.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
    {
      _id: "7",
      name: "Okona fabrics",
      category: "Castemere",
      image: "/images/img_4.jpg",
      price: 139,
      countInStock: 12,
      brand: "Okona",
      rating: 4.5,
      numReviews: 15,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
    {
      _id: "8",
      name: "Ajax Bron Fabs",
      category: "Plain and partne",
      image: "/images/img_2.jpg",
      price: 139,
      countInStock: 12,
      brand: "Ajax",
      rating: 1.5,
      numReviews: 15,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
    {
      _id: "9",
      name: "Leogos Wears",
      category: "Castemere",
      image: "/images/img_3.jpg",
      price: 190,
      countInStock: 12,
      brand: "Leogo",
      rating: 4.5,
      numReviews: 15,
      description:
        "high quality product on the fabric space app, you can trust our expertise on this space",
    },
  ],
};
